version: '3.1'
services:
  # postgres:
  #   container_name: postgres
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: mypassword
  #     POSTGRES_USER: root
  #     POSTGRES_DB: elwiz
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
    # networks:
    #   - elwiz-network

  naming-server:
    container_name: naming-server
    image: rohitshah1706/elwiz:naming-server-latest
    restart: always
    ports:
      - 8761:8761
    networks:
      - elwiz-network
    env_file:
      - ./ElWiz-NamingServer/.env

  api-gateway:
    container_name: api-gateway
    image: rohitshah1706/elwiz:api-gateway-latest
    restart: always
    depends_on:
      - naming-server
    #   - elective-service
    #   - auth-service
    ports:
      - 8001:8001
    networks:
      - elwiz-network
    env_file:
      - ./ElWiz-ApiGateway/.env
    
  elective-service:
    container_name: elective-service
    image: rohitshah1706/elwiz:elective-service-latest
    restart: always
    depends_on:
      - naming-server
    ports:
      - 8100:8100
    networks:
      - elwiz-network
    env_file:
      - ./ElWiz-ElectiveService/.env

  auth-service:
    container_name: auth-service
    image: rohitshah1706/elwiz:auth-service-latest
    restart: always
    depends_on:
      - naming-server
    ports:
      - 7070:7070
    networks:
      - elwiz-network
    env_file:
      - ./ElWiz-AuthService/.env

  frontend:
    container_name: frontend
    image: rohitshah1706/elwiz:frontend-react-latest
    restart: always
    ports:
      - 80:80
    networks:
      - elwiz-network
    env_file:
      - ./frontend-react/.env

# volumes:
#   db-data:

networks:
  elwiz-network: