# docker-compose file to run postgresql 
version: '3.1'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: root
      POSTGRES_DB: elwiz
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
