# docker-compose file to run postgresql 
version: '3.1'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: root
      POSTGRES_DB: elwiz
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - elwiz-network

  naming-server:
    container_name: naming-server
    image: rohitshah1706/elwiz:naming-server-latest
    restart: always
    ports:
      - 8761:8761
    networks:
      - elwiz-network
    
  elective-service:
    container_name: elective-service
    image: rohitshah1706/elwiz:elective-service-latest
    restart: always
    depends_on:
      - postgres
      - naming-server
    ports:
      - 8100:8100
    env_file:
      - ./ElWiz-ElectiveService/.env
    networks:
      - elwiz-network

  auth-service:
    container_name: auth-service
    image: rohitshah1706/elwiz:auth-service-latest
    restart: always
    depends_on:
      - postgres
      - naming-server
    ports:
      - 7070:7070
    env_file:
      - ./ElWiz-AuthService/.env
    networks:
      - elwiz-network

  api-gateway:
    container_name: api-gateway
    image: rohitshah1706/elwiz:api-gateway-latest
    restart: always
    depends_on:
      - naming-server
      - elective-service
      - auth-service
    ports:
      - 8001:8001
    env_file:
      - ./ElWiz-APIGateway/.env
    networks:
      - elwiz-network

volumes:
  db-data:
networks:
  elwiz-network:
