-- Create the elective table
CREATE TABLE elective (
    code VARCHAR(10) PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(500)
);

-- Insert 100 electives
INSERT INTO elective (code, name, description) VALUES
('CS101', 'Artificial Intelligence in Business', 'Explore the applications of AI in business operations and decision-making processes.'),
('CS102', 'Cybersecurity Fundamentals', 'Learn the basics of protecting computer systems and networks from cyber threats.'),
('CS103', 'Web Development with HTML5 and CSS3', 'Develop skills in building modern and responsive websites using HTML5 and CSS3.'),
('CS104', 'Mobile App Development', 'Create mobile applications for iOS and Android platforms using popular frameworks.'),
('CS105', 'Data Science and Analytics', 'Learn techniques for extracting insights from large datasets to drive data-based decision-making.'),
('CS106', 'Cloud Computing Technologies', 'Study cloud computing platforms and services and their application in various industries.'),
('CS107', 'Network Security', 'Gain knowledge of network vulnerabilities and strategies to protect against cyber attacks.'),
('CS108', 'User Experience Design', 'Explore the principles and methods of designing intuitive and user-friendly digital interfaces.'),
('CS109', 'Software Testing and Quality Assurance', 'Develop skills in testing software applications and ensuring their quality.'),
('CS110', 'Database Management Systems', 'Learn about the design, implementation, and administration of relational database systems.'),
('CS111', 'Computer Graphics and Visualization', 'Study techniques for creating and manipulating visual content using computers.'),
('CS112', 'Information Retrieval and Search Engines', 'Explore algorithms and techniques for searching and retrieving information from large datasets.'),
('CS113', 'Ethical Hacking', 'Learn ethical hacking techniques to identify and fix vulnerabilities in computer systems.'),
('CS114', 'Internet of Things (IoT)', 'Study the interconnection of physical devices and their applications in smart environments.'),
('CS115', 'Big Data Analytics', 'Learn tools and techniques to process and analyze large volumes of diverse data.'),
('CS116', 'Software Engineering', 'Gain knowledge of the software development lifecycle and best practices in software engineering.'),
('CS117', 'Digital Marketing Strategies', 'Explore strategies and tools for marketing products and services in the digital realm.'),
('CS118', 'Computer Networks', 'Study the architecture and protocols of computer networks and their administration.'),
('CS119', 'Information Systems Management', 'Learn about the management and optimization of information systems in organizations.'),
('CS120', 'Cryptography and Network Security', 'Explore encryption algorithms and network security protocols.'),
('CS121', 'E-commerce Technologies', 'Study the technologies and frameworks used in electronic commerce systems.'),
('CS122', 'Data Mining and Warehousing', 'Learn techniques for extracting valuable insights from large datasets and storing them effectively.'),
('CS124', 'Human-Computer Interaction', 'Study the interaction between humans and computers and design user-friendly interfaces.'),
('CS125', 'Digital Forensics', 'Learn techniques for collecting and analyzing digital evidence in legal investigations.'),
('CS126', 'Information Privacy and Security', 'Explore legal and ethical considerations in ensuring privacy and security of information.'),
('CS127', 'Business Intelligence and Analytics', 'Learn to leverage data to gain insights and support decision-making in organizations.'),
('CS128', 'Software Architecture and Design', 'Study the principles and methodologies for designing robust and scalable software systems.'),
('CS129', 'Cloud Infrastructure Management', 'Gain skills in managing and optimizing cloud computing infrastructure.'),
('CS130', 'Computer Vision', 'Explore algorithms and techniques for interpreting and understanding visual data.'),
('CS131', 'IT Governance and Compliance', 'Learn frameworks and strategies for ensuring compliance and governance in IT systems.'),
('CS132', 'Agile Software Development', 'Study iterative and incremental software development methodologies such as Scrum and Kanban.'),
('CS133', 'Natural Language Processing', 'Explore techniques for processing and understanding human language by computers.'),
('CS134', 'Wireless and Mobile Networks', 'Study the protocols and technologies used in wireless and mobile communications.'),
('CS135', 'IT Strategy and Innovation', 'Learn strategies for aligning IT initiatives with organizational goals and fostering innovation.'),
('CS136', 'Social Media Analytics', 'Explore tools and techniques for analyzing social media data and extracting valuable insights.'),
('CS137', 'Data Visualization', 'Develop skills in representing data visually to facilitate understanding and analysis.'),
('CS138', 'IT Ethics and Professionalism', 'Study ethical considerations and professional responsibilities in the IT field.'),
('CS139', 'Distributed Systems', 'Learn about the design and implementation of systems that span multiple computers or locations.'),
('CS140', 'IT Service Management', 'Gain knowledge of managing IT services and ensuring their alignment with business needs.'),
('CS141', 'Cloud Security', 'Explore security considerations and best practices for cloud computing environments.'),
('CS142', 'Mobile Game Development', 'Develop skills in creating interactive games for mobile platforms.'),
('CS143', 'Network Administration', 'Learn the principles and practices of administering computer networks.'),
('CS144', 'Robotic Process Automation', 'Study techniques for automating repetitive tasks using software robots.'),
('CS145', 'Virtual Reality Development', 'Explore the design and development of immersive virtual reality experiences.'),
('CS146', 'IT Risk Management', 'Learn strategies and techniques for identifying and managing IT-related risks.'),
('CS147', 'Geographical Information Systems', 'Study the collection, analysis, and visualization of spatial data.'),
('CS148', 'Embedded Systems', 'Learn about designing and programming systems with dedicated functions within larger systems.'),
('CS149', 'IT Financial Management', 'Gain knowledge of managing IT budgets, costs, and financial resources.'),
('CS150', 'Software Localization', 'Explore the process of adapting software for different languages and cultures.'),
('CS151', 'Machine Learning', 'Study algorithms and techniques that enable computers to learn from data and make predictions.'),
('CS152', 'Information Visualization', 'Explore techniques for representing complex data visually to aid understanding.'),
('CS153', 'IT Innovation and Entrepreneurship', 'Learn how to leverage technology for innovative business ideas and ventures.'),
('CS154', 'Computer Hardware and Architecture', 'Study the components and architecture of computer systems.'),
('CS155', 'Internet Security', 'Explore security challenges and solutions in the context of internet-based systems.'),
('CS156', 'Digital Image Processing', 'Study techniques for manipulating and enhancing digital images.'),
('CS157', 'IT Change Management', 'Learn strategies for managing and implementing changes to IT systems and processes.'),
('CS158', 'Social Network Analysis', 'Explore methods for analyzing social networks and understanding social relationships.'),
('CS159', 'Web Analytics', 'Learn tools and techniques for analyzing website traffic and user behavior.'),
('CS160', 'IT Outsourcing and Offshoring', 'Study the strategies and considerations involved in outsourcing IT services.'),
('CS161', 'Game Design and Development', 'Explore the principles and processes of designing and developing video games.'),
('CS162', 'Software Requirements Engineering', 'Learn techniques for eliciting, analyzing, and documenting software requirements.'),
('CS163', 'Data Warehousing', 'Study the design and implementation of data warehouses for efficient data storage and retrieval.'),
('CS164', 'Cloud Application Development', 'Develop skills in building cloud-based applications using platform-as-a-service (PaaS) technologies.'),
('CS165', 'IT Service Desk Management', 'Gain knowledge of managing and supporting IT service desks and user inquiries.'),
('CS166', 'Natural Language Generation', 'Explore techniques for automatically generating human-like text using computers.'),
('CS167', 'Information Systems Audit and Control', 'Learn strategies for auditing and controlling information systems.'),
('CS168', 'Wearable Technology', 'Study the design and development of technology that can be worn as accessories or clothing.'),
('CS169', 'IT Sustainability and Green Computing', 'Explore strategies for reducing the environmental impact of IT systems.'),
('CS170', 'Business Process Management', 'Learn methodologies and tools for modeling, analyzing, and improving business processes.'),
('CS171', 'Data Governance', 'Study the policies, processes, and technologies for managing data quality and integrity.'),
('CS172', 'Computer Simulation and Modeling', 'Explore techniques for creating and analyzing computer models of complex systems.'),
('CS173', 'IT Compliance and Regulations', 'Learn about legal and regulatory frameworks governing IT practices.'),
('CS174', 'Network Design and Optimization', 'Study the design and optimization of computer network architectures.'),
('CS175', 'Cloud Data Management', 'Gain knowledge of managing and manipulating data in cloud-based environments.'),
('CS176', 'IT Disaster Recovery and Business Continuity', 'Learn strategies for recovering IT systems and maintaining business operations during and after a disaster.'),
('CS177', 'Computer Forensics', 'Study techniques for investigating computer systems and digital evidence in criminal cases.'),
('CS178', 'Augmented Reality Development', 'Explore the design and development of interactive augmented reality experiences.'),
('CS179', 'IT Vendor Management', 'Learn strategies for managing relationships with IT vendors and ensuring service quality.'),
('CS180', 'Advanced Data Analytics', 'Study advanced techniques for analyzing and interpreting complex data.');

-- Create the student table
CREATE TABLE student (
    email VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255),
    phone_number VARCHAR(20)
);

-- Insert 30 students with unique email addresses
INSERT INTO student (email, name, phone_number) VALUES
('john@example.com', 'John Smith', '1234567890'),
('jane@example.com', 'Jane Johnson', '9876543210'),
('michael@example.com', 'Michael Davis', '4567890123'),
('sarah@example.com', 'Sarah Williams', '7890123456'),
('david@example.com', 'David Brown', '2345678901'),
('emily@example.com', 'Emily Jones', '9012345678'),
('james@example.com', 'James Taylor', '3456789012'),
('olivia@example.com', 'Olivia Miller', '6789012345'),
('william@example.com', 'William Wilson', '0123456789'),
('ava@example.com', 'Ava Anderson', '5678901234'),
('benjamin@example.com', 'Benjamin Martinez', '8901234567'),
('mia@example.com', 'Mia Thompson', '4567890123'),
('alexander@example.com', 'Alexander Garcia', '7890123456'),
('sophia@example.com', 'Sophia Robinson', '2345678901'),
('logan@example.com', 'Logan Clark', '9012345678'),
('oliver@example.com', 'Oliver Rodriguez', '3456789012'),
('amelia@example.com', 'Amelia Lewis', '6789012345'),
('lucas@example.com', 'Lucas Lee', '0123456789'),
('isabella@example.com', 'Isabella Walker', '5678901234'),
('henry@example.com', 'Henry Hall', '8901234567'),
('mia2@example.com', 'Mia Anderson', '4567890123'),
('jacob2@example.com', 'Jacob Martinez', '7890123456'),
('ava2@example.com', 'Ava Thompson', '2345678901'),
('ethan2@example.com', 'Ethan Garcia', '9012345678'),
('olivia2@example.com', 'Olivia Robinson', '3456789012'),
('daniel2@example.com', 'Daniel Clark', '6789012345'),
('sophia2@example.com', 'Sophia Rodriguez', '0123456789'),
('jackson2@example.com', 'Jackson Lewis', '5678901234'),
('emily2@example.com', 'Emily Lee', '8901234567'),
('aiden2@example.com', 'Aiden Walker', '4567890123');