spring : 
  application:
    name : api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders : "*"

server :
  port : 8001
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: /app/qqqkeystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: ${KEY_STORE_ALIAS}

eureka : 
  client : 
    serviceUrl : 
      defaultZone : http://localhost:8761/eureka




