spring : 
  application:
    name : api-gateway

server :
  port : 8001
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: /app/qqqkeystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: ${KEY_STORE_ALIAS}

eureka : 
  client : 
    serviceUrl : 
      defaultZone : ${NAMING_SERVER_URL}



