server:
  port: 7070

spring:
  datasource:
    url: jdbc:postgresql://dpg-cieq2jdgkuvlk1hui6qg-a.singapore-postgres.render.com:5432/elwiz
    username: root
    password: X5hFqsXSCJqnfHej5JDVvzH2zU16hA4O

  application :
    name : auth-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka :
  client :
    serviceUrl :
      defaultZone : http://localhost:8761/eureka