server:
  port: 8100

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  application :
    name : elective-service

springdoc:
  swagger-ui:
    path: /elective-service/docs

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka :
  client :
    serviceUrl :
      defaultZone : ${NAMING_SERVER_URL}

