name: CICD for Elwiz ApiGateway

on:
  push:
    branches: [main]
    paths:
      - ElWiz-ApiGateway/**
  pull_request:
    branches: [main]
    paths:
      - ElWiz-ApiGateway/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: |
        cd ElWiz-ApiGateway
        mvn clean install

    - name: Log files in pwd
      run: ls -al

    - name: Log files in pwd
      run: ls -al

    - name: Upload ElWiz-ApiGateway Dockerfile artifact
      uses: actions/upload-artifact@v2
      with:
        name: Dockerfile
        path: ElWiz-ApiGateway/Dockerfile
        retention-days: 1

    - name: Upload ElWiz-ApiGateway.jar artifact
      uses: actions/upload-artifact@v2
      with:
        name: ElWiz-ApiGateway.tar
        path: ElWiz-ApiGateway/target/ElWiz-ApiGateway.jar
        retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Dockerfile artifact
      uses: actions/download-artifact@v2
      with:
        name: Dockerfile
        path: ElWiz-ApiGateway

    - name: Download ElWiz-ApiGateway.jar artifact
      uses: actions/download-artifact@v2
      with:
        name: ElWiz-ApiGateway.tar
        path: ElWiz-ApiGateway/target
    
    - name: Build image & push to docker hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: rohitshah1706/elwiz
        tags: api-gateway-latest
        registry: docker.io
        directory: ElWiz-ApiGateway
        dockerfile: ElWiz-ApiGateway/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
        