name: CICD for Elwiz Auth Service

on:
  push:
    branches: [main]
    paths:
      - ElWiz-AuthService/**
  pull_request:
    branches: [main]
    paths:
      - ElWiz-AuthService/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: elwiz
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=5s --health-timeout=3s --health-retries=2

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Log docker running services
      run: docker ps -a

    - name: Build with Maven
      run: |
        cd ElWiz-AuthService
        mvn clean install

    - name: Log files in pwd
      run: ls -al

    - name: Upload ElWiz-AuthService Dockerfile artifact
      uses: actions/upload-artifact@v2
      with:
        name: Dockerfile
        path: ElWiz-AuthService/Dockerfile
        retention-days: 1

    - name: Upload ElWiz-AuthService.jar artifact
      uses: actions/upload-artifact@v2
      with:
        name: ElWiz-AuthService.tar
        path: ElWiz-AuthService/target/ElWiz-AuthService.jar
        retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Dockerfile artifact
      uses: actions/download-artifact@v2
      with:
        name: Dockerfile
        path: ElWiz-AuthService

    - name: Download ElWiz-AuthService.jar artifact
      uses: actions/download-artifact@v2
      with:
        name: ElWiz-AuthService.tar
        path: ElWiz-AuthService/target
    
    - name: Build image & push to docker hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: rohitshah1706/elwiz
        tags: auth-service-latest
        registry: docker.io
        directory: ElWiz-AuthService
        dockerfile: ElWiz-AuthService/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
        