name: CICD for Elwiz Auth Service

on:
  push:
    branches: [main]
    paths:
      - ElWiz-AuthService/**
  pull_request:
    branches: [main]
    paths:
      - ElWiz-AuthService/**
  workflow_dispatch:

jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

  SetupEnv: 
    runs-on: ubuntu-latest
    needs: Checkout
    services:
      mysql: 
        image: mysql:8.0 
        env:
          # get the root password from the secrets
          MYSQL_ROOT_PASSWORD: mypassword
          MYSQL_DATABASE: elwiz
        ports:
          - 3306:3306 
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=3s --health-retries=2
    steps:
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

  Build:
    runs-on: ubuntu-latest
    needs: SetupEnv
    steps:
    - name: Log docker running services
      run: docker ps -a
    - name: Build with Maven
      run: |
        cd ElWiz-AuthService
        mvn clean install
            
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: Deploy to Dockerhub
      run: |
        echo "Deploying to Dockerhub"


