name: CICD for Elwiz Elective Service

on:
  push:
    branches: [main]
    paths:
      - ElWiz-ElectiveService/**
  pull_request:
    branches: [main]
    paths:
      - ElWiz-ElectiveService/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: |
        cd ElWiz-ElectiveService
        mvn clean install

    - name: Log files in pwd
      run: ls -al

    - name: Build image & push to docker hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: rohitshah1706/elwiz
        tags: elective-service-latest
        registry: docker.io
        directory: ElWiz-ElectiveService
        dockerfile: ElWiz-ElectiveService/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 