name: CICD for Elwiz Elective Service

on:
  push:
    branches: [main]
    paths:
      - ElWiz-ElectiveService/**
  pull_request:
    branches: [main]
    paths:
      - ElWiz-ElectiveService/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql: 
        image: mysql:8.0 
        env:
          # get the root password from the secrets
          MYSQL_ROOT_PASSWORD: mypassword
          MYSQL_DATABASE: elwiz
        ports:
          - 3306:3306 
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=3s --health-retries=2

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Log docker running services
      run: docker ps -a

    - name: Build with Maven
      run: |
        cd ElWiz-ElectiveService
        mvn clean install

    - name: Log files in pwd
      run: ls -al

    - name: Upload ElWiz-ElectiveService Dockerfile artifact
      uses: actions/upload-artifact@v2
      with:
        name: Dockerfile
        path: ElWiz-ElectiveService/Dockerfile
        retention-days: 1

    - name: Upload ElWiz-ElectiveService.jar artifact
      uses: actions/upload-artifact@v2
      with:
        name: ElWiz-ElectiveService.tar
        path: ElWiz-ElectiveService/target/ElWiz-ElectiveService.jar
        retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Dockerfile artifact
      uses: actions/download-artifact@v2
      with:
        name: Dockerfile
        path: ElWiz-ElectiveService

    - name: Download ElWiz-ElectiveService.jar artifact
      uses: actions/download-artifact@v2
      with:
        name: ElWiz-ElectiveService.tar
        path: ElWiz-ElectiveService/target
    
    - name: Build image & push to docker hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: rohitshah1706/elwiz
        tags: elective-service-latest
        registry: docker.io
        directory: ElWiz-ElectiveService
        dockerfile: ElWiz-ElectiveService/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 