name: CICD for Naming Server

on:
  push:
    branches: [main]
    paths:
      - ElWiz-NamingServer/**
  pull_request:
    branches: [main]
    paths:
      - ElWiz-NamingServer/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: |
        cd ElWiz-NamingServer
        mvn clean install

    - name: Log files in pwd
      run: ls -al

    - name: Upload ElWiz-NamingServer Dockerfile artifact
      uses: actions/upload-artifact@v2
      with:
        name: Dockerfile
        path: ElWiz-NamingServer/Dockerfile
        retention-days: 1

    - name: Upload ElWiz-NamingServer.jar artifact
      uses: actions/upload-artifact@v2
      with:
        name: ElWiz-NamingServer.tar
        path: ElWiz-NamingServer/target/ElWiz-NamingServer.jar
        retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Dockerfile artifact
      uses: actions/download-artifact@v2
      with:
        name: Dockerfile
        path: ElWiz-NamingServer

    - name: Download ElWiz-NamingServer.jar artifact
      uses: actions/download-artifact@v2
      with:
        name: ElWiz-NamingServer.tar
        path: ElWiz-NamingServer/target
    
    - name: Build image & push to docker hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: rohitshah1706/elwiz
        tags: naming-server-latest
        registry: docker.io
        directory: ElWiz-NamingServer
        dockerfile: ElWiz-NamingServer/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
        