name: CICD for Naming Server

on:
  push:
    branches: [main]
    paths:
      - ElWiz-NamingServer/**
  pull_request:
    branches: [main]
    paths:
      - ElWiz-NamingServer/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log files in pwd
      run: ls -al

    - name: Build image & push to docker hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: rohitshah1706/elwiz
        tags: naming-server-latest
        registry: docker.io
        directory: ElWiz-NamingServer
        dockerfile: ElWiz-NamingServer/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 